:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+AUTHOR: Marcio Woitek
#+TITLE: Quiz: A Medical Device Example
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \renewcommand{\labelitemi}{$\rhd$}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \setlist[itemize]{leftmargin=*}
#+LATEX_HEADER: \setlist{nosep}
#+OPTIONS: ':t
#+OPTIONS: author:nil
#+OPTIONS: date:nil
#+OPTIONS: title:nil
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

* Problem 1

*Answer:* 3\\

There are three decision variables, \( x_1 \), \( x_2 \) and \( x_3 \). The
variable \( x_i \) corresponds to the number of pig valves purchased from the
\( i \)-th supplier.

* Problem 2

*Answer:* \( 0.4x_1+0.3x_2+0.2x_3\geq 500 \)\\

In total, \( x_1 \) valves are purchased from supplier 1. In this case, the
number of large valves is 40% of the total. Then \( 0.4x_1 \) large valves are
purchased from supplier 1. A similar argument allows us to conclude that
- \( 0.3x_2 \) large valves are purchased from supplier 2, and
- \( 0.2x_3 \) large valves are purchased from supplier 3.
Therefore, the total number of large valves can be expressed as
\( 0.4x_1+0.3x_2+0.2x_3 \). At least 500 such valves need to be purchased every
month. Hence the following must hold:
\begin{equation}
0.4x_1+0.3x_2+0.2x_3\geq 500.
\end{equation}

* Problem 3

*Answer:* \( 0.4x_1+0.35x_2+0.2x_3\geq 300 \)\\

In total, \( x_1 \) valves are purchased from supplier 1. In this case, the
number of medium valves is 40% of the total. Then \( 0.4x_1 \) medium valves are
purchased from supplier 1. A similar argument allows us to conclude that
- \( 0.35x_2 \) medium valves are purchased from supplier 2, and
- \( 0.2x_3 \) medium valves are purchased from supplier 3.
Therefore, the total number of medium valves can be expressed as
\( 0.4x_1+0.35x_2+0.2x_3 \). At least 300 such valves need to be purchased every
month. Hence the following must hold:
\begin{equation}
0.4x_1+0.35x_2+0.2x_3\geq 300.
\end{equation}

* Problem 4

*Answer:* \( 0.2x_1+0.35x_2+0.6x_3\geq 300 \)\\

In total, \( x_1 \) valves are purchased from supplier 1. In this case, the
number of small valves is 20% of the total. Then \( 0.2x_1 \) small valves are
purchased from supplier 1. A similar argument allows us to conclude that
- \( 0.35x_2 \) small valves are purchased from supplier 2, and
- \( 0.6x_3 \) small valves are purchased from supplier 3.
Therefore, the total number of small valves can be expressed as
\( 0.2x_1+0.35x_2+0.6x_3 \). At least 300 such valves need to be purchased every
month. Hence the following must hold:
\begin{equation}
0.2x_1+0.35x_2+0.6x_3\geq 300.
\end{equation}

* Problem 5

*Answer:* Decision variables

* Problem 6

*Answer:* Objective function coefficients

* Problem 7

*Answer:* Constraint function coefficients

* Problem 8

*Answer:* ~SUMPRODUCT($B$4:$D$4,B10:D10)~

* Problem 9

*Answer:* All of the above

* Problem 10

*Answer:* \( \$ 6450 \)

# Local Variables:
# ispell-alternate-dictionary: "american"
# End:
