:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+AUTHOR: Marcio Woitek
#+TITLE: Quiz: Dorian Auto Manufacturer
#+LATEX_HEADER: \usepackage[a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage[american]{babel}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[sc]{mathpazo}
#+LATEX_HEADER: \linespread{1.05}
#+LATEX_HEADER: \renewcommand{\labelitemi}{$\rhd$}
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \setlist[itemize]{leftmargin=*}
#+LATEX_HEADER: \setlist{nosep}
#+OPTIONS: ':t
#+OPTIONS: author:nil
#+OPTIONS: date:nil
#+OPTIONS: title:nil
#+OPTIONS: toc:nil
#+STARTUP: hideblocks

#+BEGIN_SRC latex
\thispagestyle{empty}
\pagestyle{empty}
#+END_SRC

* Problem 1

*Answer:* 2\\

There are two decision variables, \( x_1 \) and \( x_2 \). \( x_1 \) denotes the
number of 1-min comedy ads purchased, and \( x_2 \) denotes the number of 1-min
football ads purchased.

* Problem 2

*Answer:*
\begin{equation*}
\min\quad Z=50x_1+100x_2
\end{equation*}
#+BEGIN_SRC latex
\vspace{0.1cm}
#+END_SRC
\( x_1 \) 1-min comedy ads are purchased. The corresponding cost is \( 50x_1 \).
Similarly, the cost of \( x_2 \) 1-min football ads is \( 100x_2 \). Then the
total cost can be expressed as \( Z=50x_1+100x_2 \). The goal is to minimize
this cost. This means we need to find \( \min Z \).

* Problem 3

*Answer:* 2\\

There are two constraints:
- one specifying the minimum number of high-income women that need to be reached;
- one specifying the minimum number of high-income men that need to be reached.

* Problem 4

*Answer:* \( 7x_1+2x_2\geq 28 \)\\

\( x_1 \) comedy ads will be seen by \( 7,000,000x_1 \) high-income women.
Similarly, \( x_2 \) football ads will be seen by \( 2,000,000x_2 \) high-income
women. In total, \( 7,000,000x_1+2,000,000x_2 \) such women will be reached.
Since we want this number to be at least 28,000,000, the following must hold:
\begin{align*}
  7,000,000x_1+2,000,000x_2&\geq 28,000,000\\
  7x_1+2x_2&\geq 28
\end{align*}

* Problem 5

*Answer:* \( 2x_1+12x_2\geq 24 \)\\

\( x_1 \) comedy ads will be seen by \( 2,000,000x_1 \) high-income men.
Similarly, \( x_2 \) football ads will be seen by \( 12,000,000x_2 \)
high-income men. In total, \( 2,000,000x_1+12,000,000x_2 \) such men will be
reached. Since we want this number to be at least 24,000,000, the following must
hold:
\begin{align*}
  2,000,000x_1+12,000,000x_2&\geq 24,000,000\\
  2x_1+12x_2&\geq 24
\end{align*}

* Problem 6

*Answer:* \( (4,0) \) and \( (0,14) \)\\

Actually, to answer this question, no plot is necessary. We can simply check
whether the points satisfy the line equation we were given. Clearly, one of the
points is \( (4,0) \):
\begin{align*}
  7x_1+2x_2&=7\cdot 4+2\cdot 0\\
  &=28+0\\
  &=28.
\end{align*}
The other point is \( (0,14) \), since
\begin{align*}
  7x_1+2x_2&=7\cdot 0+2\cdot 14\\
  &=0+28\\
  &=28.
\end{align*}

* Problem 7

*Answer:* \( (12,0) \) and \( (0,2) \)\\

Actually, to answer this question, no plot is necessary. We can simply check
whether the points satisfy the line equation we were given. Clearly, one of the
points is \( (12,0) \):
\begin{align*}
  2x_1+12x_2&=2\cdot 12+12\cdot 0\\
  &=24+0\\
  &=24.
\end{align*}
The other point is \( (0,2) \), since
\begin{align*}
  2x_1+12x_2&=2\cdot 0+12\cdot 2\\
  &=0+24\\
  &=24.
\end{align*}

* Problem 8

*Answer:* This problem has an unbounded feasible region.\\

In this case, a plot would help. But it is given to us in the next question. So
I see no point in re-creating this plot. The image in problem 9 clearly shows
that the feasible region is unbounded. I could have reached the same conclusion
by looking at the constraints. After all, there is no constraint that specifies
an upper bound.

* Problem 9

*Answer:* \( \$ 320\mathrm{k} \)\\

The graph shows that the optimal solution corresponds to the point \( E \). This
point lies in the intersection of the following lines:
\begin{align*}
  7x_1+2x_2&=28,\\
  2x_1+12x_2&=24.
\end{align*}
Next, we use the second equation to derive an expression for \( x_1 \):
\begin{align*}
  2x_1+12x_2&=24\\
  x_1+6x_2&=12\\
  x_1&=12-6x_2
\end{align*}
The next step is to substitute this result into the first line equation:
\begin{align*}
  7x_1+2x_2&=28\\
  7(12-6x_2)+2x_2&=28\\
  84-42x_2+2x_2&=28\\
  -40x_2&=-56\\
  40x_2&=56\\
  5x_2&=7\\
  x_2&=\frac{7}{5}\\
  x_2&=1.4
\end{align*}
Hence:
\begin{equation*}
x_1=12-6x_2=12-6\cdot 1.4=3.6.
\end{equation*}
Therefore, the optimal value of the cost is
\begin{equation}
Z^{*}=50\cdot 3.6+100\cdot 1.4=320.
\end{equation}
Recall that the unit of \( Z \) is \( \$ 1,000 \). Then the minimum cost is
\( \$ 320,000 \). Notice that this is the same value shown in the plot.

* Problem 10

*Answer:* All of the above
